### ISSUE TITLE
Build fails on production environment

### ISSUE THREAD

**Issue by retroriff** [nuxt-community/color-mode-module#108]
I am not able to build on Netlify. The module works in development environment, but it fails on Netlify when `NODE_ENV` is set to `production`:

> 
✖ Nuxt Fatal Error                                       │                              │
> Error: Cannot find module '@nuxtjs/color-mode'           │
> Require stack:                                           │
> /opt/build/repo/node_modules/@nuxt/core/dist/core.js  

```js
"devDependencies": {
    "@nuxtjs/color-mode": "^2.1.1",
}
```
On Netlify my `NODE_VERSION` is `14`.

**Comment by an-nadaa** [comment]
@retroriff do you mind explaining how you fixed this issue if you did? I am facing the same problem

**Comment by an-nadaa** [comment]
The problem was that i have manually set `NODE_ENV` in the environment variables which was disabling dev deps installs `WARNING: The environment variable 'NODE_ENV' is set to 'production'. Any 'devDependencies' in package.json will not be installed`. Hope this helps anyone who faced the same problem.
