### ISSUE TITLE
Does this module support SCSS styling as well?

### ISSUE THREAD

**Issue by rajesh-h** [nuxt-community/color-mode-module#13]
Hi,

I am currently following this blog post/github repo.
https://github.com/bdrtsky/nuxt-dev-to-clone

I am trying to apply Dark mode toggle, but I am kind of stuck as in how to use this module on scss styling.

I am guessing I should make some changes here in this file
https://github.com/bdrtsky/nuxt-dev-to-clone/blob/master/assets/styles/tokens.scss

Am I correct?

**Comment by rajesh-h** [comment]
@bdrtsky could you please assist me how to apply the changes on SCSS?

**Comment by bdrtsky** [comment]
Hello @rajesh-h sure you can add dark mode anywhere with this modules. Let me help you with that. Actually I can add dark mode to `nuxt-dev-to-clone` so you could check complete example. Can you please create issue in `nuxt-dev-to-clone` repo since it's not actually the issue with this module? Thanks!

**Comment by rajesh-h** [comment]
Sure Doing it right away. Thank you very much.
