### ISSUE TITLE
Cannot read property 'preference' of undefined

### ISSUE THREAD

**Issue by hut-a-massmediagroup-100** [nuxt-community/color-mode-module#25]
### Version
@nuxtjs/color-mode: v1.0.3
nuxt: v2.14.3

### Steps to reproduce
I just created a new project, and installed last version of this module. After that i faced with next error:

`TypeError: Cannot read property 'preference' of undefined
    at he (app.2637907.js:1)
    at app.2637907.js:1
    at h (app.6209d6e.js:2)
    at Generator._invoke (app.6209d6e.js:2)
    at Generator.next (app.6209d6e.js:2)
    at r (app.6209d6e.js:2)
    at l (app.6209d6e.js:2)`

mode: 'spa'.
That error is only if i tried to run `nuxt start`

The same issue closed [https://github.com/nuxt-community/color-mode-module/issues/21](url), but nothing changed.

### What is Expected?
No error, and correctly work)

**Comment by hut-a-massmediagroup-100** [comment]
The first time, where i caused this error, was, when i updated more part of plugins/modules(nuxt and color-mode too). Then i did rollback to the previous version of nuxt and color-mode, and that dropped error. But i wanna use fresh releases)

**Comment by Atinux** [comment]
Hi @hut-a-massmediagroup-100 

Can you please create a reproduction on CodeSandBox? I cannot reproduce the bug.

**Comment by Allezxandre** [comment]
I'm not the OP, but this issue also happens to me when I enable modern mode on a SPA-mode (`ssr` set to `false`) Nuxt-TypeScript project and then use `nuxt-ts generate -m`. The issue is resolved if I don't use modern mode to generate the code. 

Unfortunately I have been unable to create a reproduction on the JS CodeSandBox ([here is my failed attempt](https://codesandbox.io/s/nuxt-dark-tailwindcss-forked-xby35?file=/nuxt.config.js)).

However, I have been able to find the culprit in the following "compiled" code: 

```javascript
// [...]
    c.a.component('ColorScheme', Dr);
    var Ar = JSON.parse('{"path":"/","sameSite":"lax"}'),
    Nr = window.__NUXT_COLOR_MODE__,
    Mr = function (r, o) {
      var data = r.nuxtState.colorMode;
      data || (data = {
        preference: Nr.preference,
        value: Nr.value,
        unknown: 'system' === Nr.preference
      });
// [...]
```

`Nr` apparently is undefined, which might indicate that the evaluation of `window.__NUXT_COLOR_MODE__` failed. I hope this helps.

**Comment by Atinux** [comment]
Hi @Allezxandre 

I found the issue, if you use `ssr: false` and `nuxt start`, **you need to move `@nuxtjs/color-mode` from `buildModules` to  `modules`**.

This way, the script injecting `window.__NUXT_COLOR_MODE__` can be injected at runtime.

**Comment by Allezxandre** [comment]
Thank you!

**Comment by rezaansarirad** [comment]
its work thank you!
